version: "3.9"
services:
  api:
    container_name: api
    build:
      context: .
      target: development
    ports:
      - 8000:8000
    volumes:
      - .:/opt/app/
    environment:
      - ENVIRONMENT=local
      - DJANGO_SETTINGS_MODULE=settings.local
      - SECRET_KEY=secret_key
      - ALLOWED_HOSTS=localhost
      - DB_HOST=database
      - DB_USER=lolek
      - DB_PASSWORD=tajne
      - DB_NAME=db
      - DB_PORT=5432
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=lolek
      - POSTGRES_PASSWORD=tajne
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data

